//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DxChinook.Data.XPO.Models
{

	[Persistent(@"Album")]
	public partial class XPAlbum : XPLiteObject
	{
		int _AlbumId;
		[Key(true)]
		public int AlbumId
		{
			get { return _AlbumId; }
			set { SetPropertyValue<int>(nameof(AlbumId), ref _AlbumId, value); }
		}
		string _Title;
		[Size(160)]
		public string Title
		{
			get { return _Title; }
			set { SetPropertyValue<string>(nameof(Title), ref _Title, value); }
		}
		XPArtist _ArtistId;
		[Association(@"XPAlbumReferencesXPArtist")]
		public XPArtist ArtistId
		{
			get { return _ArtistId; }
			set { SetPropertyValue<XPArtist>(nameof(ArtistId), ref _ArtistId, value); }
		}
		[Association(@"XPTrackReferencesXPAlbum")]
		public XPCollection<XPTrack> Tracks { get { return GetCollection<XPTrack>(nameof(Tracks)); } }
	}

}
