//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DxChinook.Data.XPO.Models
{

	[Persistent(@"Artist")]
	public partial class XPArtist : XPLiteObject
	{
		int _ArtistId;
		[Key(true)]
		public int ArtistId
		{
			get { return _ArtistId; }
			set { SetPropertyValue<int>(nameof(ArtistId), ref _ArtistId, value); }
		}
		string _Name;
		[Size(120)]
		public string Name
		{
			get { return _Name; }
			set { SetPropertyValue<string>(nameof(Name), ref _Name, value); }
		}
		[Association(@"XPAlbumReferencesXPArtist")]
		public XPCollection<XPAlbum> Albums { get { return GetCollection<XPAlbum>(nameof(Albums)); } }
	}

}
