//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DxChinook.Data.XPO.Models
{

	[Persistent(@"Customer")]
	public partial class XPCustomer : XPLiteObject
	{
		int _CustomerId;
		[Key(true)]
		public int CustomerId
		{
			get { return _CustomerId; }
			set { SetPropertyValue<int>(nameof(CustomerId), ref _CustomerId, value); }
		}
		string _FirstName;
		[Size(40)]
		public string FirstName
		{
			get { return _FirstName; }
			set { SetPropertyValue<string>(nameof(FirstName), ref _FirstName, value); }
		}
		string _LastName;
		[Size(20)]
		public string LastName
		{
			get { return _LastName; }
			set { SetPropertyValue<string>(nameof(LastName), ref _LastName, value); }
		}
		string _Company;
		[Size(80)]
		public string Company
		{
			get { return _Company; }
			set { SetPropertyValue<string>(nameof(Company), ref _Company, value); }
		}
		string _Address;
		[Size(70)]
		public string Address
		{
			get { return _Address; }
			set { SetPropertyValue<string>(nameof(Address), ref _Address, value); }
		}
		string _City;
		[Size(40)]
		public string City
		{
			get { return _City; }
			set { SetPropertyValue<string>(nameof(City), ref _City, value); }
		}
		string _State;
		[Size(40)]
		public string State
		{
			get { return _State; }
			set { SetPropertyValue<string>(nameof(State), ref _State, value); }
		}
		string _Country;
		[Size(40)]
		public string Country
		{
			get { return _Country; }
			set { SetPropertyValue<string>(nameof(Country), ref _Country, value); }
		}
		string _PostalCode;
		[Size(10)]
		public string PostalCode
		{
			get { return _PostalCode; }
			set { SetPropertyValue<string>(nameof(PostalCode), ref _PostalCode, value); }
		}
		string _Phone;
		[Size(24)]
		public string Phone
		{
			get { return _Phone; }
			set { SetPropertyValue<string>(nameof(Phone), ref _Phone, value); }
		}
		string _Fax;
		[Size(24)]
		public string Fax
		{
			get { return _Fax; }
			set { SetPropertyValue<string>(nameof(Fax), ref _Fax, value); }
		}
		string _Email;
		[Size(60)]
		public string Email
		{
			get { return _Email; }
			set { SetPropertyValue<string>(nameof(Email), ref _Email, value); }
		}
		XPEmployee _SupportRep;
		[Persistent(@"SupportRepId")]
		[Association(@"XPCustomerReferencesXPEmployee")]
		public XPEmployee SupportRep
		{
			get { return _SupportRep; }
			set { SetPropertyValue<XPEmployee>(nameof(SupportRep), ref _SupportRep, value); }
		}
		[PersistentAlias("[SupportRep.EmployeeId]")]
		public int SupportRepID
		{
			get { return (int)(EvaluateAlias(nameof(SupportRepID))); }
		}
		[Association(@"XPInvoiceReferencesXPCustomer")]
		public XPCollection<XPInvoice> Invoices { get { return GetCollection<XPInvoice>(nameof(Invoices)); } }
	}

}
