//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DxChinook.Data.XPO.Models
{

	[Persistent(@"Genre")]
	public partial class XPGenre : XPLiteObject
	{
		int _GenreId;
		[Key(true)]
		public int GenreId
		{
			get { return _GenreId; }
			set { SetPropertyValue<int>(nameof(GenreId), ref _GenreId, value); }
		}
		string _Name;
		[Size(120)]
		public string Name
		{
			get { return _Name; }
			set { SetPropertyValue<string>(nameof(Name), ref _Name, value); }
		}
		[Association(@"XPTrackReferencesXPGenre")]
		public XPCollection<XPTrack> Tracks { get { return GetCollection<XPTrack>(nameof(Tracks)); } }
	}

}
