//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DxChinook.Data.XPO.Models
{

	[Persistent(@"InvoiceLine")]
	public partial class XPInvoiceLine : XPLiteObject
	{
		int _InvoiceLineId;
		[Key(true)]
		public int InvoiceLineId
		{
			get { return _InvoiceLineId; }
			set { SetPropertyValue<int>(nameof(InvoiceLineId), ref _InvoiceLineId, value); }
		}
		XPInvoice _InvoiceId;
		[Association(@"XPInvoiceLineReferencesXPInvoice")]
		public XPInvoice InvoiceId
		{
			get { return _InvoiceId; }
			set { SetPropertyValue<XPInvoice>(nameof(InvoiceId), ref _InvoiceId, value); }
		}
		XPTrack _TrackId;
		[Association(@"XPInvoiceLineReferencesXPTrack")]
		public XPTrack TrackId
		{
			get { return _TrackId; }
			set { SetPropertyValue<XPTrack>(nameof(TrackId), ref _TrackId, value); }
		}
		decimal _UnitPrice;
		public decimal UnitPrice
		{
			get { return _UnitPrice; }
			set { SetPropertyValue<decimal>(nameof(UnitPrice), ref _UnitPrice, value); }
		}
		int _Quantity;
		public int Quantity
		{
			get { return _Quantity; }
			set { SetPropertyValue<int>(nameof(Quantity), ref _Quantity, value); }
		}
	}

}
