//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DxChinook.Data.XPO.Models
{

	[Persistent(@"MediaType")]
	public partial class XPMediaType : XPLiteObject
	{
		int _MediaTypeId;
		[Key(true)]
		public int MediaTypeId
		{
			get { return _MediaTypeId; }
			set { SetPropertyValue<int>(nameof(MediaTypeId), ref _MediaTypeId, value); }
		}
		string _Name;
		[Size(120)]
		public string Name
		{
			get { return _Name; }
			set { SetPropertyValue<string>(nameof(Name), ref _Name, value); }
		}
		[Association(@"XPTrackReferencesXPMediaType")]
		public XPCollection<XPTrack> Tracks { get { return GetCollection<XPTrack>(nameof(Tracks)); } }
	}

}
